TRUNCATE TABLE terox.productos  RESTART IDENTITY CASCADE;
TRUNCATE TABLE terox.usuarios  RESTART IDENTITY CASCADE;
TRUNCATE TABLE terox.imagenes  RESTART IDENTITY CASCADE;
TRUNCATE TABLE terox.ordenes  RESTART IDENTITY CASCADE;
TRUNCATE TABLE terox.identidad_fiscal  RESTART IDENTITY CASCADE;
TRUNCATE TABLE terox.facturas  RESTART IDENTITY CASCADE;
